# Generated by Django 5.1 on 2024-09-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_snippet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='user',
        ),
    ]
